export const welcome_message = [ "What's on the agenda today?",
  "Got a question? Ask me anything.",
  "Your AI buddy is listening...",
  "Need help brainstorming?",
  "Tell me your thoughts!",
  "What problem are we solving today?",
  "Curious about something? Go ahead!",
  "Ready to explore some ideas?",
  "Let's make progress together.",
  "Looking for inspiration?",
  "What's troubling your mind?",
  "I'm here, ask away.",
  "Want to try something new?",
  "Let's learn something today!",
  "What challenge are you facing?"]